name: Node.js CI/CD (Self-hosted Runner)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --production

      - name: Update production code
        run : |
          cd ~/rsi-bcc-softwarehouse-backend
          git fetch origin master
          git reset --hard origin/master
          npm install --production

      - name: Restart PM2 app
        run: |
          cd ~/rsi-bcc-softwarehouse-backend
          pm2 restart app || pm2 start server.js --name "app"
